# Generated by Django 5.2.13 on 2026-05-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='custom_amount',
            new_name='isa',
        ),
    ]
